Lesson2
NMadiyar/Kolesa-Upgrade-FE-2021 pull request #3
Opened 2021-09-26 10:14 UTC by NMadiyar

Доработал верстку, сделал мердж с лессон1, изменил прозрачность, убрал бордеры с кнопок при актив состоянии, пофиксил маржины между ними и добавил нулевые маржин на ферст чайлд элементы, убрал пустые строки, удалил ненужный код с картинкой, пофиксил маржин между тайтлом и прайсом

2021-09-26 16:09 UTC, airtwister requested changes

2021-09-26 16:09 UTC, airtwister commented on index.html
> +                        <img src="src/assets/Group%2074.png" alt="points" height="68" width="196">
чот тут так и картинка, должна быть полноценная верстка

2021-09-26 16:46 UTC, airtwister commented
и этот коммент не решён

https://github.com/NMadiyar/Kolesa-Upgrade-FE-2021/pull/2#discussion_r716137802

2021-09-27 14:40 UTC, NMadiyar commented on index.html
> +                        <img src="src/assets/Group%2074.png" alt="points" height="68" width="196">
Запушил коммит, сделал верстку

2021-09-28 03:39 UTC, airtwister approved these changes

2021-09-28 08:44 UTC, merged