Lesson4
NMadiyar/Kolesa-Upgrade-FE-2021 pull request #4
Opened 2021-09-29 17:57 UTC by NMadiyar

Cделана верстка страницы

2021-09-30 14:54 UTC, airtwister commented
вообще lesson3 должен быть)

2021-09-30 14:55 UTC, airtwister commented
В условиях задачи сказано что футер должен быть прибит к низу экрана даже если нет контента. (можно гуглить как стики футер)

![image](https://user-images.githubusercontent.com/5547378/135479325-f98adfcf-f5a0-4809-b9ad-1754277e9fb0.png)

2021-09-30 14:57 UTC, airtwister commented
нет полоски у активного элемента (см в фигме)

![image](https://user-images.githubusercontent.com/5547378/135479752-3a8b4b77-6815-4dd6-be27-2376b4af2084.png)

2021-09-30 14:58 UTC, airtwister commented
нет бордер радиуса у главного баннера

![image](https://user-images.githubusercontent.com/5547378/135479992-84c8a394-2e60-4d8b-b130-e96d715d1ddf.png)

2021-09-30 15:01 UTC, airtwister commented
весь блок должен быть как кнопка а не отдельные элементы. вот условия - https://docs.google.com/document/d/1YBFr14pO-0agZ3G_bPuD8hqIXLJpA5YgukXLOivyU2w/edit?usp=drive_web&authuser=1

![image](https://user-images.githubusercontent.com/5547378/135480490-ed4a86ac-fbe6-4e9e-b48d-5348fb392618.png)

2021-09-30 15:11 UTC, airtwister commented
1. Текст должен быть красным при ховере
2. "New" непонятно где находится (и в обычном состоянии и при ховере)
3. Между карточками должно быть 24px (и по бокам и сверху/снизу)
4. При ховере карточка не должна толкать остальные, а как бы чуть "наезжать" на нижнюю, чтобы всё не дергалось

![image](https://user-images.githubusercontent.com/5547378/135481274-4d6c4cc6-da1c-4507-9717-f68531ea8996.png)

2021-09-30 15:12 UTC, airtwister commented
в футере падинг есть только с левой стороны, нужно сделать с двух сторон и кратно 4 (там - 32px)

2021-09-30 15:14 UTC, airtwister commented
не очень удобно так переходит чтобы посмотреть верстку, поставь лучше этот файл рядом с index.html и назови main.html

![image](https://user-images.githubusercontent.com/5547378/135482711-89e751d8-148e-4671-9342-a52f3c21b198.png)

2021-09-30 15:15 UTC, airtwister commented
по условиям, при клике инпут должен фокусироваться

![image](https://user-images.githubusercontent.com/5547378/135482932-f4b9d351-54f9-4c79-a100-df92e9af7acf.png)

2021-09-30 15:19 UTC, airtwister requested changes

2021-09-30 15:19 UTC, airtwister commented on src/js/main.js
> +document.querySelector('#app');
это зачем?)

2021-09-30 15:19 UTC, airtwister commented on src/pages/main_banner.html
> +
между строками кода должна быть максимум одна пустая строка

отступы по всему файлу нужно поправить

2021-10-01 13:49 UTC, NMadiyar commented on src/js/main.js
> +document.querySelector('#app');
Блин, я короче с самого начала тестил с сассом, хотел через сасс все сделать и  тут он как фреймворк подключает данные, думал сработает, создал другой хтмл файл и обернул его в апп1, и так же подключать стили через отдельные компоненты сасса, но все шло криво, в итоге просто создал другой хтмл файл и подключил большой файл с css, а этот код забыл удалить)

2021-10-02 17:46 UTC, airtwister commented
по макету полоска не должна толкать текст (все текста меню выровнены по одной линии)

![image](https://user-images.githubusercontent.com/5547378/135726940-2c8e48d1-0f43-4781-b818-27b2c1a654b3.png)

2021-10-02 17:47 UTC, airtwister commented
из-за баттона появился align=center 

![image](https://user-images.githubusercontent.com/5547378/135726957-a9bec7bd-bd94-45b0-81cc-dd0fb951ce02.png)

2021-10-02 17:50 UTC, airtwister commented
шрифт, цвет текста и отступы не те)

![image](https://user-images.githubusercontent.com/5547378/135727036-6a0f6c38-1f17-43ca-b8b2-1760b65366ae.png)

2021-10-02 17:52 UTC, airtwister commented
повылазило при ховере

![image](https://user-images.githubusercontent.com/5547378/135727065-e6e1d7d8-808e-4979-8ef4-c21e5629b29d.png)

2021-10-02 17:52 UTC, airtwister approved these changes

2021-10-02 17:52 UTC, airtwister commented on main.html
> +            <div class="header__avatar__pts">300 баллов</d>
походу ты случайно стер и тут </d> вместо </div>, это лучше поправить, из-за этого не собирается **yarn dev**

я апрув в любом случае поставлю, ты почини и замерджи

2021-10-05 12:09 UTC, merged