Lesson4
NMadiyar/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-06 01:31 UTC by NMadiyar

Переделал под стандарты сасса, добавил некоторые стили, изменил файл на index.html, исправил футер, хедер, работаю над карточками и навбаром

2021-10-07 07:42 UTC, airtwister requested changes

2021-10-07 07:42 UTC, airtwister commented on index1.html
> +<!DOCTYPE html>
зачем этот файл или почему так назван?

2021-10-07 07:42 UTC, airtwister commented on index1.html
> +    <title>Vite App</title>
поехали отступы в head

2021-10-07 07:42 UTC, airtwister commented on index.html
> +<!--    <link rel="stylesheet" href="src/css/main_banner.css">-->
лучше не коментить, а удалять. если надо будет найдешь по git history

2021-10-07 07:42 UTC, airtwister commented on src/styles/vars.scss
> +.container {
лучше не хранить стили рядом с переменными, можно вынести в общий файл

2021-10-07 07:42 UTC, airtwister commented on src/styles/main_content.scss
> +                background: #5cef5c;
по заданию надо использовать переменные для всех цветов

2021-10-07 07:42 UTC, airtwister commented on src/styles/nav.scss
> +        &-bold {
через две черточки модификатор

2021-10-07 07:42 UTC, airtwister commented on index1.html
> +                    <div class="modal__content__balance">
тут и ниже такое же:
если создаешь второй элемент, значит, это повод вынести его в отдельный блок, как раз здесь можешь использовать **микс** из задания, что-то типа такого `<div class="modal__balance balance-info">`

2021-10-09 04:08 UTC, NMadiyar commented on index1.html
> +<!DOCTYPE html>
этот файл с модалкой, не знал как его назвать, думал его удалить, так же думал что мб пригодится)

2021-10-10 04:18 UTC, merged